# wrangler.toml
name = 'soaringhot'
main = "worker.js"
compatibility_date = "2024-01-01"

# Static assets — put index.html in a /public folder and uncomment:
# [site]
# bucket = "./public"

[[d1_databases]]
binding = "DB"                  # matches env.DB in worker.js
database_name = "soaring_hot"
database_id = "466e8019-e45e-4c7c-93be-ba46b9159bf3"   # from: wrangler d1 create coffee-cart-db
